<html>
<head>
    <title>DownloadStation Decrypter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    <form action="<?php echo $_SERVER['PHP_SELF']?>" enctype="multipart/form-data" method="POST" role="form">
        <input type="hidden" name="action" value="dlcDecrypt">
        <div class="header">
            <ul class="nav nav-pills pull-right">
            </ul>
            <h3 class="text-muted">DownloadStation Decrypter</h3>
        </div>

        <div class="jumbotron">
            <h2>Decrypter:</h2>
            <select name="decType" class="form-control">
                <option value="<?php echo $this->decDcrypt?>">dcrypt.it</option>
                <option value="<?php echo $this->decLinkdecrypter?>">linkdecrypter.com</option>
            </select>
        </div>

        <div class="row marketing">
            <div class="col-lg-12">
                <div class="form-group" style="margin-top:15px;">
                    <label for="url">Enter URL to dlc:</label>
                    <input type="text" class="form-control" id="url" name="dlcUrl" placeholder="e.g. http://ncrypt.in/container/dlc/698edd9235235jh23g5jh235235hg23.dlc">
                </div>
                <input type="submit" name="actionDlcUrl" value="Extract from DLC URL" class="btn btn-success">
                <div class="form-group" style="margin-top:15px;">
                    <label for="actionDlcContents">Enter DLC contents:</label>
                    <textarea class="form-control" rows="3" wrap="auto" cols="77" name="dlcContents" placeholder="e.g. mMmqWutI4D3XDkr5xa1RzXjNPYJMQhj....."></textarea>
                </div>
                <input type="submit" name="actionDlcContents" value="Extract from DLC contents" class="btn btn-success">
                <div class="form-group" style="margin-top:15px;">
                    <label for="dlcFile">Upload DLC file:</label>
                    <input type="file" id="dlcFile" name="dlcFile">
                    <p class="help-block">Upload a DLC File.</p>
                </div>
                <input type="submit" name="actionDlcFile" value="Extract from DLC file" class="btn btn-success">
            </div>

            <div class="col-lg-12">
                <br><br>
                <p>Nothing of the above. Take me straight to where I can enter my links directly:</p>
                <input type="submit" name="actionEnterLinks" class="btn btn-success" value="ENTER LINKS MANUALLY!" >
            </div>
    </form>
</div>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.js"></script>
</body>
</html>