<html>
<head>
    <title>DownloadStation Decrypter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    <form action="<?php echo $_SERVER['PHP_SELF']?>" method="POST" role="form">
        <input type="hidden" name="action" value="addLinks">
        <div class="header">
            <ul class="nav nav-pills pull-right"></ul>
            <h3 class="text-muted">DownloadStation Decrypter</h3>
        </div>

        <div class="row marketing">
            <div class="col-lg-12">
                <div class="form-group" style="margin-top:15px;">
                    <label for="links">You may edit the links prior submitting them to Download Station:</label>
                    <textarea class="form-control" wrap="auto" rows="30" id="links" name="links"><?php echo $this->links?></textarea>
                    <br/>
                    <div class="text-right">
                        <input type="submit" name="filenameLookup" value="Lookup filenames" class="btn btn-success" >
                    </div>
                </div>
                <input type="text" name="unpackPasswd" class="form-control" placeholder="Password to unrar/unzip (optional)"><br/>
                <input type="password" class="form-control" id="passwd" name="passwd" placeholder="Password for Web-API-Login if not set in config (optional)"><br/><br/>
                <div class="text-center">
                    <input type="submit" value="Add links (finish)" class="btn btn-success" >
                    <span class="btn btn-warning" onClick="history.go(0)">Start over (RESET)</span>
                </div>
            </div>
    </form>
</div>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.js"></script>
</body>
</html>