<html>
<head>
    <title>DownloadStation Decrypter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    <form action="<?php echo $_SERVER['PHP_SELF']?>" method="POST" role="form">
        <div class="header">
            <ul class="nav nav-pills pull-right">
            </ul>
            <h3 class="text-muted">DownloadStation Decrypter</h3>
        </div>

        <div class="jumbotron">
            <h2>You may edit the links prior submitting them to Download Station:</h2>
            <input type="hidden" name="action" value="addLinks">
            <textarea class="form-control" wrap="auto" rows="30" name="links"><?php echo $this->links?></textarea></br>
            <input type="text" name="unpackPasswd" class="form-control" placeholder="Password to unrar/unzip (optional)"><br/>
            <input type="password" class="form-control" id="passwd" name="passwd" placeholder="Password for Web-API-Login if not set in config (optional)">
            <br/><input type="submit" value="ADD LINKS (FINISH)" class="btn btn-success" >
            <span class="btn btn-warning" onClick="history.go(0)">Start over (RESET)</span>

        </div>
    </form>
</div>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.js"></script>
</body>
</html>